# Site settings
title:          WIEBLOG
tagline:             'encia200(위준영)'
description:    "안녕하세요, 위준영의 블로그입니다.<br/>encia200@gmail.com"
baseurl:        ""
url:            "https://www.wiejoonyoung.com"
enforce_ssl: www.wiejoonyoung.com

github:
  repo:              https://github.com/encia200

# Author
author:
  name:         WIE JOON YOUNG
  url:          https://www.wiejoonyoung.com
  email:        encia200@gmail.com

# Build settings
markdown:       kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    default_lang: c++
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems ... move to Gemfile
# plugins:
#   - jekyll-paginate

# Permalinks
# permalink:      /:year-:month-:day/:title
  permalink:           date
  relative_permalinks: false

# paginate
paginate:       100

# Comments
disqus: wiejoonyoung

# Analytics
google_analytics:
  ua: UA-117932332-1

# navigation
# navigation:
#   - title: About
#     url: /about
#   - title: /Edu
#     url: /edu
#   - title: Links
#     url: /links
#   - title: Categories
#     url: /category
#   - title: Posts
#     url: /index.html

# collections
# collections:
#   tags:
#     outpout: true
#     permalink: /tags/:path/

# # defaults
# defaults:
#   - scope:
#       path: ""
#       type: tags
#     values:
#       layout: tag

# atom:
#   buildCommand:
#     - jekyll
#     - build
#     - --option
#     - --this
#   buildEnv:
#     JEKYLL_ENV: development
#   postDirs:
#     - _newsletters
#   defaultPostDir: _drafts

mermaid:
  src: '/js/mermaid.js'
