# Site settings
title:          WIEBLOG
description:    "Hello World!"
baseurl:        ""
url:            "https://www.wiejoonyoung.com"
enforce_ssl: www.wiejoonyoung.com

# Author
author:
  name:         WIE JOON YOUNG
  url:          https://www.wiejoonyoung.com
  email:        encia200@gmail.com

# Build settings
markdown:       kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    default_lang: c++
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       100

disqus: wiejoonyoung
highlighter: rouge
