# Site settings
title:          WJY
description:    "Hello World!"
baseurl:        ""
url:            "https://www.wiejoonyoung.com"
enforce_ssl: www.wiejoonyoung.com

# Author
author:
  name:         WIE JOON YOUNG
  url:          https://www.wiejoonyoung.com
  email:        encia200@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# jekyll-sitemap should be after other plugins.
# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

disqus: wiejoonyoung
